### ISSUE TITLE
Differences to bazelisk

### ISSUE THREAD

**Issue by ah-edg** [salesforce/bazenv#2]
Hi,
this project looks similar to https://github.com/bazelbuild/bazelisk
which is mature, hosted in the official bazel organization, maintained by a Bazel maintainer  and already mentioned in the documentation of some of the other rules (I forgot which, but probably somewhere in rules_docker or rules_go).

Maybe you want to cooperate or merge your efforts?
Otherwise I think you should add a section in the README where you describe the differences and pros/cons in detail.

**Comment by rmichela** [comment]
This project is indeed similar to bazelisk and reviewing bazelisk's features with the latest release, the two are basically the same. 

Here's something funny, when you google [install multiple bazel versions](https://www.google.com/search?q=install+multiple+bazel+versions) nothing mentions bazelisk, and the top result suggests using your own shell script. If you don't know what you are looking for, bazelisk isn't easy to find. 😆 

Also, when I started bazenv, bazelisk was a python script. Due to many prior bad experiences, I've developed an aversion to other people's python, preferring the repeatability of go.

Finally, developing bazenv was fun and scratched an itch. 😁 I learned more about go in the process. I do hope bazenv and bazelisk can happily coexist.

**Comment by ah-edg** [comment]
That's totally fine and I get it!

I just want to add that I think the issue sounds a little harsh - so here's some backstory: I found this project not because I need it but while browsing your Twitter feed. Because I really dig what you're doing with grpc. I just hoped bazelisk might help you if you don't know it already.

**Comment by rmichela** [comment]
> I just want to add that I think the issue sounds a little harsh

Not at all! Text on the internet never quite caries our emotional intent. Don't worry about it.
